# NumPyの基本

In [1]:
import numpy as np

In [2]:
np.exp(2)

7.38905609893065

In [3]:
np.log(np.e)

1.0

In [4]:
np.sin(np.pi)

1.2246467991473532e-16

In [6]:
np.sqrt(3)

1.7320508075688772

## NumPyの配列

In [7]:
a = np.array([2, 3, 5, 7, 8])
a[0]

2

In [8]:
a[1:3]

array([3, 5])

In [9]:
a[2:-1]

array([5, 7])

In [11]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [13]:
c = np.arange(1, 3, 0.2)
c

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [14]:
a.dtype

dtype('int64')

In [15]:
c.dtype

dtype('float64')

In [17]:
d = np.array([1, 2, 3], dtype=np.float64)
d

array([1., 2., 3.])

In [19]:
d.dtype

dtype('float64')

In [21]:
e = np.arange(5.)
e

array([0., 1., 2., 3., 4.])

In [22]:
e.dtype

dtype('float64')

# 二次元配列

In [23]:
a = np.array([[2, 3, 4], [5, 6, 7]], dtype=np.float64)
a

array([[2., 3., 4.],
       [5., 6., 7.]])

In [24]:
a[0, 1]

3.0

In [25]:
a[:, 1]

array([3., 6.])

In [26]:
a[1, :]

array([5., 6., 7.])

In [27]:
a[0, 2:]

array([4.])

In [28]:
a[0, :2]

array([2., 3.])

## 配列のデータ属性

In [29]:
a = np.arange(15.).reshape(3, 5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [30]:
a.shape

(3, 5)

In [31]:
a.ndim

2

In [32]:
a.size

15

In [33]:
b = np.arange(4.)
b.shape

(4,)

In [34]:
b.ndim

1

In [35]:
b.size

4

## reshapeメソッドと形状の変更

In [39]:
a = np.arange(16.)
c = a.reshape(4, -1)
c

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [37]:
c.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [40]:
c.reshape(-1)#==c.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [42]:
b = np.arange(4.)
b.reshape(-1, 1)

array([[0.],
       [1.],
       [2.],
       [3.]])

In [43]:
b[:, np.newaxis]#==b.reshape(-1, 1)

array([[0.],
       [1.],
       [2.],
       [3.]])

In [44]:
b[:, None]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [45]:
b.reshape(1, -1)

array([[0., 1., 2., 3.]])

In [46]:
b[np.newaxis, :]

array([[0., 1., 2., 3.]])

## その他の配列の操作

In [47]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
b = np.ones((2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [51]:
c = np.empty((2, 5))
c

array([[1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8]])

In [52]:
d = np.linspace(0, 1, 10)
d

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## 行列の連結

In [54]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
b = np.array([[6, 7, 8], [9, 10, 11]])
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
np.r_[a, b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
np.c_[a, b]

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [58]:
c = np.arange(3)
d = np.arange(3, 6)

In [59]:
c

array([0, 1, 2])

In [60]:
d

array([3, 4, 5])

In [61]:
np.r_[c, d]

array([0, 1, 2, 3, 4, 5])

In [62]:
np.c_[c, d]

array([[0, 3],
       [1, 4],
       [2, 5]])

In [63]:
np.r_[a, c] #形状が合わないとエラー

ValueError: all the input arrays must have same number of dimensions

In [64]:
np.r_[a, c.reshape(1, -1)]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

>-一次元配列の場合は縦ベクトルと見なされる。<br>

In [67]:
c.shape

(3,)

In [68]:
c.reshape(1, -1).shape

(1, 3)