# 配列の基本計算

In [2]:
import numpy as np

In [3]:
a = np.arange(5.)
a

array([0., 1., 2., 3., 4.])

In [4]:
a.sum()

10.0

In [5]:
a.mean()

2.0

In [6]:
a.max()

4.0

In [7]:
a.min()

0.0

In [10]:
#二次元配列の場合
b = np.arange(9.).reshape(3, 3)
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [11]:
b.sum()

36.0

In [12]:
b.sum(axis=0)

array([ 9., 12., 15.])

In [13]:
b.sum(axis=1)

array([ 3., 12., 21.])

>-axis=0を指定すると行ごと、axis=1を指定すると列ごとの合計を出します。

<br>

## ブロードキャスト

NumPyの配列には、その配列を含む演算を行う場合二次元数や形状を自動的に調整する機能があります。これをブロードキャストといいます。

In [14]:
a = np.arange(3., 8.)
a

array([3., 4., 5., 6., 7.])

In [15]:
np.exp(a)

array([  20.08553692,   54.59815003,  148.4131591 ,  403.42879349,
       1096.63315843])

In [16]:
np.log(a)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015])

In [17]:
np.sqrt(a)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131])

In [18]:
b = np.arange(9.).reshape(3, 3)
b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [19]:
np.exp(b)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

>このように配列に関数を作用させると全要素に対してその関数を計算する操作をすることになり、この操作をブロードキャストと呼びます。<br>
ユニバーサル関数も呼ばれる。

In [20]:
#ブロードキャストは関数だけでなく演算子にも使える。
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
a + 3

array([3, 4, 5, 6, 7])

In [22]:
a * 3

array([ 0,  3,  6,  9, 12])

In [23]:
a ** 3

array([ 0,  1,  8, 27, 64])

In [24]:
a >= 2

array([False, False,  True,  True,  True])

In [25]:
a != 3

array([ True,  True,  True, False,  True])

In [31]:
b = np.arange(9).reshape(3, 3)
b > 3

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

>ブロードキャストは高速

In [32]:
a = np.array([10, 20, 30, 40])
b = np.array([False, True, True, False])

In [33]:
a[b]

array([20, 30])

In [34]:
c = np.array([[3, 4, 5], [6, 7, 8]])
c

array([[3, 4, 5],
       [6, 7, 8]])

In [35]:
d = np.array([[False, False, True], [False, True, True]])
d

array([[False, False,  True],
       [False,  True,  True]])

In [36]:
c[d]

array([5, 7, 8])

In [37]:
a = np.arange(10)
a[a > 5]

array([6, 7, 8, 9])

In [38]:
a[(a >= 3) & (a < 6)]

array([3, 4, 5])

In [39]:
a[(a < 2) | (a > 7)]

array([0, 1, 8, 9])

In [40]:
a[a % 3 != 0]

array([1, 2, 4, 5, 7, 8])

>ブロードキャストにおいて論理演算子はand, or ではなく &, | を使う。

## 配列の演算

In [41]:
u = np.arange(4)
v = np.arange(3, 7)

In [42]:
u

array([0, 1, 2, 3])

In [43]:
v

array([3, 4, 5, 6])

In [44]:
u + v

array([3, 5, 7, 9])

In [45]:
u - v

array([-3, -3, -3, -3])

In [46]:
u * v

array([ 0,  4, 10, 18])

In [47]:
np.dot(u, v)

32

In [49]:
np.dot(u.reshape(1, -1), v)

array([32])

In [50]:
(u * v).sum()

32

In [51]:
# 二次元配列の演算
a = np.arange(9.).reshape(3, 3)
b = np.arange(4., 13.).reshape(3, 3)

In [52]:
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [53]:
b

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [54]:
a + b

array([[ 4.,  6.,  8.],
       [10., 12., 14.],
       [16., 18., 20.]])

In [55]:
a - b

array([[-4., -4., -4.],
       [-4., -4., -4.],
       [-4., -4., -4.]])

In [56]:
a * b

array([[ 0.,  5., 12.],
       [21., 32., 45.],
       [60., 77., 96.]])

In [57]:
a / b

array([[0.        , 0.2       , 0.33333333],
       [0.42857143, 0.5       , 0.55555556],
       [0.6       , 0.63636364, 0.66666667]])

In [58]:
np.dot(a, b)

array([[ 27.,  30.,  33.],
       [ 90., 102., 114.],
       [153., 174., 195.]])

In [59]:
a.dot(b)

array([[ 27.,  30.,  33.],
       [ 90., 102., 114.],
       [153., 174., 195.]])

In [60]:
a@b

array([[ 27.,  30.,  33.],
       [ 90., 102., 114.],
       [153., 174., 195.]])

In [61]:
#形状の違う行列の積
a = np.arange(9.).reshape(3, 3)
v = np.arange(1., 4.)
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [62]:
v

array([1., 2., 3.])

In [63]:
np.dot(a, v)

array([ 8., 26., 44.])

In [64]:
u = v.reshape(-1, 1)

In [65]:
u.shape

(3, 1)

In [67]:
v.shape

(3,)

In [69]:
np.dot(a, u)

array([[ 8.],
       [26.],
       [44.]])

In [70]:
w = v.reshape(1, -1)
w

array([[1., 2., 3.]])

In [71]:
np.dot(w, a)

array([[24., 30., 36.]])

In [72]:
# 配列同士の演算におけるブロードキャスト
a = np.arange(12.).reshape(4, 3)
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [74]:
b = np.arange(3.).reshape(1, 3)
c = np.arange(4.).reshape(4, 1)
b

array([[0., 1., 2.]])

In [75]:
c

array([[0.],
       [1.],
       [2.],
       [3.]])

In [76]:
a + b

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.],
       [ 9., 11., 13.]])

In [77]:
a * c

array([[ 0.,  0.,  0.],
       [ 3.,  4.,  5.],
       [12., 14., 16.],
       [27., 30., 33.]])

In [78]:
b - c

array([[ 0.,  1.,  2.],
       [-1.,  0.,  1.],
       [-2., -1.,  0.],
       [-3., -2., -1.]])