# 乱数

In [2]:
import numpy as np

In [3]:
np.random.rand()#[0, 1)の範囲の浮動小数点数を返す

0.6915654684855993

In [4]:
np.random.rand(3, 2)#引数を指定すると配列で返す

array([[0.66546757, 0.8924004 ],
       [0.43328019, 0.26767576],
       [0.63417394, 0.74924142]])

In [5]:
np.random.rand(5)#

array([0.49019272, 0.90332926, 0.54733602, 0.81179713, 0.39537573])

In [6]:
np.random.randint(4)#引数未満0以上の整数を返す

3

In [7]:
np.random.randint(5, size=(3, 3))# sizeを指定するとその配列で返す

array([[2, 1, 3],
       [1, 3, 3],
       [0, 3, 3]])

## 再現性と乱数の種

In [8]:
np.random.seed(10)

In [9]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [10]:
np.random.rand(5)

array([0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [11]:
np.random.seed(10)

In [12]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [13]:
np.random.rand(5)

array([0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [14]:
def throw_dice(n, random_seed=10):
    np.random.seed(random_seed)
    return np.random.randint(1, 7, size=n).sum()


In [15]:
throw_dice(10)

34

In [16]:
throw_dice(10)

34

In [17]:
throw_dice(100)

328

In [18]:
throw_dice(100)

328

In [19]:
#よくない実装例

class Dice:
    def __init__(self):
        np.random.seed(0)
        self.sum_ = 0
        
    def throw(self):
        self.sum_ += np.random.randint(1, 7)
    
    def get_sum(self):
        return self.sum_
    

In [20]:
d1 = Dice()
for _ in range(10):
    d1.throw()

d1.get_sum()

39

In [21]:
d2 = Dice()
for _ in range(10):
    d2.throw()

d2.get_sum()

39

In [25]:
d1 = Dice()
d2 = Dice()
d3 = Dice()

for _ in range(10):
    d1.throw()
    d2.throw()
#     d3.throw()

print(d1.get_sum())
print(d2.get_sum())
# print(d3.get_sum())

34
33


d1を作った後にすぐにd２を作っており、それぞれ定義されている乱数の種が異なる。<br>

>ではインスタンスごとに乱数の再現性を保証するには？

In [26]:
#RandomStateクラスを使う
rs = np.random.RandomState(10)
rs.rand()

0.771320643266746

In [27]:
rs.rand()

0.0207519493594015

In [28]:
class Dice2:
    def __init__(self, random_seed=None):
        self.random_state_ = np.random.RandomState(random_seed)
        self.sum_ = 0
    
    def throw(self):
        self.sum_ += self.random_state_.randint(1, 7)
    
    def get_sum(self):
        return self.sum_
    

In [31]:
d1 = Dice2(1)
d2 = Dice2(1)

for _ in range(10):
    d1.throw()
    d2.throw()
    

In [32]:
print(d1.get_sum())
print(d2.get_sum())

32
32
