# 乱数

In [1]:
import numpy as np

In [3]:
np.random.rand()#[0, 1)の範囲の浮動小数点数を返す

0.7040905051091009

In [4]:
np.random.rand(3, 2)#引数を指定すると配列で返す

array([[0.82364907, 0.33494765],
       [0.43645074, 0.92883306],
       [0.5200838 , 0.84011738]])

In [5]:
np.random.rand(5)#

array([0.99260413, 0.67475122, 0.10931368, 0.95486428, 0.82191633])

In [13]:
np.random.randint(4)#引数未満0以上の整数を返す

2

In [14]:
np.random.randint(5, size=(3, 3))# sizeを指定するとその配列で返す

array([[2, 1, 2],
       [1, 4, 2],
       [3, 4, 1]])

## 再現性と乱数の種

In [15]:
np.random.seed(10)

In [16]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [17]:
np.random.rand(5)

array([0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [18]:
np.random.seed(10)

In [19]:
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [20]:
np.random.rand(5)

array([0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [21]:
def throw_dice(n, random_seed=10):
    np.random.seed(random_seed)
    return np.random.randint(1, 7, size=n).sum()


In [23]:
throw_dice(10)

34

In [24]:
throw_dice(10)

34

In [25]:
throw_dice(100)

328

In [26]:
throw_dice(100)

328

In [27]:
#よくない実装例

class Dice:
    def __init__(self):
        np.random.seed(0)
        self.sum_ = 0
        
    def throw(self):
        self.sum_ += np.random.randint(1, 7)
    
    def get_sum(self):
        return self.sum_
    